# fly.toml app configuration file generated for ecmp186-nhom06 on 2026-02-24T08:21:19+07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'ecmp186-nhom06'
primary_region = 'sin'

[build]
  dockerfile = 'docker/Dockerfile'

[[mounts]]
  source = 'uploads'
  destination = '/var/www/html/public/assets/images'

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = 'off'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[[vm]]
  memory = '256mb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 256
