app = 'ecmp186-nhom06'
primary_region = 'sin'

[build]
  dockerfile = 'docker/Dockerfile'

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[[mounts]]
  source = "uploads"
  destination = "/var/www/html/public/assets/images"

[[vm]]
  memory = '256mb'
  cpus = 1
  memory_mb = 256